name: Build Godot Executeable

on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Godot Build
        id: build
        # workaround for https://github.com/yeslayla/build-godot-action/issues/30
        uses: manleydev/build-godot-action@f759ed7f8fcb5137cb70873ecf663aa8a1bd998b
        with:
          name: Quiz4Everyone
          preset: ${{ matrix.os }}
          debugMode: ${{ github.event_name != 'push' || github.ref != 'main' }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Quiz4Everyone_${{ matrix.os }}
          path: ${{ steps.build.outputs.build }}
